export default {
  colors: {
    black: "black",
    white: "white",
    text: "black",
    primary: "#2421CF",
    gray: "#F1F1F1",
    orange: "#FF823D",
    green: "#00FF00",
    green100: "#00FF00",
    green200: "#00ED00",
    green300: "#00DC00",
    green400: "#00C500",
    green500: "#00AD00",
    green600: "#009B00",
    purple: "#7A4BFF",
    purple100: "#C2AEFF",
    purple200: "#AC8EFF",
    purple300: "#9975FF",
    purple400: "#875CFF",
    purple500: "#7747FF",
    purple600: "#5E25FF",
  },
  fonts: {
    display: "'Helvetica Now Display', system-ui, sans-serif",
    body: "'Helvetica Now Text', system-ui, sans-serif",
    serif: "'Times Now', system-ui, serif",
    mono: "'IMB Plex Mono', system-ui, sans-serif",
  },
  fontWeights: {
    bold: 700,
    medium: 600,
    regular: 500,
    extraLight: 300,
  },
  lineHeights: {
    leadingNone: 1,
    leadingTight: 1.25,
    leadingSnug: 1.375,
    leadingNormal: 1.5,
    leadingRelaxed: 1.625,
    leadingLoose: 2,
  },
  text: {
    display: {
      color: "inherit",
      fontFamily: "display",
      lineHeight: "leadingTight",
      fontWeight: "regular",
      mt: 0,
      mb: [3, 4, 5],
    },
    body: {
      color: "inherit",
      fontFamily: "body",
      lineHeight: "leadingNormal",
      fontWeight: "regular",
      mt: 0,
      mb: 0,
    },
    serif: {
      color: "inherit",
      fontFamily: "serif",
      lineHeight: "leadingTight",
      fontWeight: "extraLight",
      mt: 0,
      mb: 0,
      strong: {
        fontFamily: "display",
        fontWeight: "medium",
        mt: 0,
        mb: 0,
      },
      a: {
        fontFamily: "display",
        fontWeight: "medium",
        mt: 0,
        mb: 0,
      },
    },
    mono: {
      color: "inherit",
      fontFamily: "mono",
      lineHeight: "leadingNormal",
      fontWeight: "regular",
      mt: 0,
      mb: 0,
    },
    buttonBlur: {
      position: "relative",
      display: "inline-flex",
      variant: "text.display",
      m: "0 auto !important",
      "a:nth-of-type(1)": {
        position: "absolute",
        left: 0,
        transform: "translateX(-50%)",
        zIndex: 1,
        color: "white",
        border: "none",
        whiteSpace: "nowrap",
      },
      "a:nth-of-type(2)": {
        position: "absolute",
        left: 0,
        transform: "translateX(-50%)",
        color: "primary",
        backgroundColor: "primary",
        border: "none",
        whiteSpace: "nowrap",
      },
    },
  },
  styles: {
    super: {
      variant: "text.display",
      fontSize: [3, 4, 5],
      fontWeight: "bold",
      textTransform: "uppercase",
    },
    display: {
      variant: "text.display",
      fontSize: [12, 13, 14],
      fontWeight: "medium",
      wordBreak: "break-all",
    },
    mono: {
      variant: "text.mono",
      fontSize: [0, 1, 2],
      textTransform: "uppercase",
    },
    intro: {
      variant: "text.serif",
      fontSize: [5, 6, 7],
      mt: [9, 10, 11],
      mb: [5, 6, 7],
    },
    introLarge: {
      variant: "text.serif",
      fontSize: [9, 10, 11],
      textAlign: ["justify", "justify", "center"],
      p: {
        m: 0,
      },
    },
    copyLight: {
      fontFamily: "display",
      fontSize: [2, 3, 4],
      fontWeight: "extraLight",
    },
    html: {
      variant: "text.body",
      p: { variant: "text.body", mb: 4 },
      a: { variant: "text.body", mb: 4 },
    },
    pressKit: {
      variant: "text.buttonBlur",
      a: {
        pt: ["15px", "15px", "15px"],
        pb: ["17px", "17px", "17px"],
        px: ["30px", "30px", "50px"],
        fontSize: [6, 6, 7],
        borderRadius: "50px",
        "&:last-of-type": {
          filter: "blur(9px)",
        },
      },
    },
    sendMessage: {
      variant: "text.buttonBlur",
      a: {
        pt: ["10px"],
        pb: ["11px"],
        px: ["20px"],
        fontSize: [3],
        borderRadius: "25px",
        textTransform: "initial",
        "&:last-of-type": {
          color: "purple",
          backgroundColor: "purple",
          filter: "blur(4px)",
        },
      },
    },
    postLink: {
      variant: "text.display",
      fontSize: [3, 4, 5],
      fontWeight: "medium",
      py: 3,
      px: 3,
      mb: 0,
      backgroundColor: "purple",
      color: "white",
      display: "block",
      border: "none",
      "&:nth-of-type(1)": {
        backgroundColor: "purple100",
      },
      "&:nth-of-type(2)": {
        backgroundColor: "purple200",
      },
      "&:nth-of-type(3)": {
        backgroundColor: "purple300",
      },
      "&:nth-of-type(4)": {
        backgroundColor: "purple400",
      },
      "&:nth-of-type(5)": {
        backgroundColor: "purple500",
      },
      "&:nth-of-type(6)": {
        backgroundColor: "purple600",
      },
    },
    navLink: {
      variant: "text.display",
      display: "flex",
      alignItems: "flex-start",
      fontSize: 9,
      fontWeight: "medium",
      height: "38px",
      letterSpacing: -0.9,
      backgroundColor: "purple",
      color: "white",
      border: "none",
      m: "0 !important",
      p: 4,
      span: {
        display: "inline-block",
        fontSize: 3,
        mt: "6px",
        mr: 5,
      },
      "&:nth-of-type(1)": {
        backgroundColor: "purple200",
      },
      "&:nth-of-type(2)": {
        backgroundColor: "purple300",
      },
      "&:nth-of-type(3)": {
        backgroundColor: "purple400",
      },
      "&:nth-of-type(4)": {
        backgroundColor: "purple500",
      },
      "&:nth-of-type(5)": {
        backgroundColor: "purple600",
      },
    },
    navFooter: {
      variant: "text.display",
      display: "flex",
      alignItems: "center",
      fontSize: 9,
      fontWeight: "medium",
      height: "38px",
      letterSpacing: -0.9,
      backgroundColor: "purple",
      color: "white",
      border: "none",
      m: "0 !important",
      p: 4,
    },
    label: {
      variant: "text.body",
      pt: 3,
      pb: 2,
      px: 3,
      border: "none",
      color: "black",
      backgroundColor: "orange",
      fontSize: [1, 1, 2],
    },
    input: {
      variant: "text.display",
      pt: 2,
      pb: 4,
      px: 3,
      mb: 2,
      outline: "none",
      border: "none",
      borderRadius: 0,
      color: "white",
      backgroundColor: "orange",
      letterSpacing: -0.9,
      fontSize: [6, 6, 7],
      "::placeholder": {
        color: "white",
      },
    },
    button: {
      variant: "text.display",
      px: 4,
      height: "50px",
      outline: "none",
      border: "none",
      borderRadius: 0,
      color: "white",
      backgroundColor: "orange",
      fontSize: [4, 4, 5],
      fontWeight: "medium",
      cursor: "pointer",
      "::placeholder": {
        color: "white",
      },
    },
  },
  fontSizes: [8, 10, 12, 13, 15, 16, 20, 24, 28, 30, 32, 48, 64, 72, 84],
  space: [0, 4, 8, 14, 16, 32, 48, 56, 64, 72, 84, 96, 128, 256, 512],
}
