export default {
  colors: {
    black: "black",
    white: "white",
    text: "black",
    primary: "#2421CF",
    gray: "#F1F1F1",
    orange: "#FF823D",
    green: "#00FF00",
    green100: "#00FF00",
    green200: "#00ED00",
    green300: "#00DC00",
    green400: "#00C500",
    green500: "#00AD00",
    green600: "#009B00",
    purple: "#7A4BFF",
    purple100: "#C2AEFF",
    purple200: "#AC8EFF",
    purple300: "#9975FF",
    purple400: "#875CFF",
    purple500: "#7747FF",
    purple600: "#5E25FF",
  },
  fonts: {
    display: "'Helvetica Now Display', system-ui, sans-serif",
    body: "'Helvetica Now Text', system-ui, sans-serif",
    serif: "'Times Now', system-ui, serif",
    mono: "'IMB Plex Mono', system-ui, sans-serif",
  },
  fontWeights: {
    bold: 700,
    medium: 600,
    regular: 500,
    extraLight: 300,
  },
  lineHeights: {
    body: 1.5,
    mono: 1.2,
    heading: 1.2,
    display: 1,
  },
  text: {
    display: {
      color: "text",
      fontFamily: "display",
      lineHeight: "heading",
      fontWeight: "regular",
      mt: 0,
      mb: 0,
    },
    body: {
      color: "text",
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "regular",
      mt: 0,
      mb: 0,
      p: { mt: 0, mb: 0 },
    },
    serif: {
      color: "text",
      fontFamily: "serif",
      lineHeight: "heading",
      fontWeight: "extraLight",
      mt: 0,
      mb: 0,
      strong: {
        fontFamily: "display",
        fontWeight: "medium",
        mt: 0,
        mb: 0,
      },
      a: {
        fontFamily: "display",
        fontWeight: "medium",
        mt: 0,
        mb: 0,
      },
    },
    mono: {
      color: "text",
      fontFamily: "mono",
      lineHeight: "mono",
      fontWeight: "regular",
      mt: 0,
      mb: 0,
    },
    buttonBlur: {
      position: "relative",
      display: "inline-flex",
      variant: "text.display",
      m: "0 auto",
      "a:nth-of-type(1)": {
        position: "absolute",
        left: 0,
        transform: "translateX(-50%)",
        zIndex: 1,
        color: "white",
        border: "none",
        whiteSpace: "nowrap",
      },
      "a:nth-of-type(2)": {
        position: "absolute",
        left: 0,
        transform: "translateX(-50%)",
        color: "white",
        backgroundColor: "primary",
        border: "none",
        whiteSpace: "nowrap",
      },
    },
  },
  styles: {
    super: {
      variant: "text.display",
      fontSize: 5,
      fontWeight: "bold",
      textTransform: "uppercase",
    },
    display: {
      variant: "text.display",
      fontSize: 14,
      fontWeight: "medium",
    },
    mono: {
      variant: "text.mono",
      fontSize: 2,
      textTransform: "uppercase",
    },
    intro: {
      variant: "text.serif",
      fontSize: 7,
    },
    introLarge: {
      variant: "text.serif",
      fontSize: 11,
    },
    copyLight: {
      fontFamily: "display",
      fontSize: 4,
      fontWeight: "extraLight",
    },
    html: {
      variant: "text.body",
      p: { variant: "text.body" },
      a: { variant: "text.body", lineHeight: "display" },
    },
    pressKit: {
      variant: "text.buttonBlur",
      a: {
        py: 4,
        px: 5,
        fontSize: 7,
        borderRadius: "50px",
        "&:last-of-type": {
          filter: "blur(9px)",
        },
      },
    },
    postLink: {
      variant: "text.display",
      fontSize: 5,
      fontWeight: "medium",
      py: 3,
      px: 3,
      backgroundColor: "purple",
      color: "white",
    },
    label: {
      variant: "text.body",
      pt: 3,
      pb: 2,
      px: 3,
      border: "none",
      color: "black",
      backgroundColor: "orange",
      fontSize: 2,
    },
    input: {
      variant: "text.display",
      pt: 2,
      pb: 4,
      px: 3,
      mb: 2,
      outline: "none",
      border: "none",
      borderRadius: 0,
      color: "white",
      backgroundColor: "orange",
      fontSize: 7,
      "::placeholder": {
        color: "white",
      },
    },
    button: {
      variant: "text.display",
      px: 4,
      height: "50px",
      outline: "none",
      border: "none",
      borderRadius: 0,
      color: "white",
      backgroundColor: "purple",
      fontSize: 5,
      fontWeight: "medium",
      cursor: "pointer",
      "::placeholder": {
        color: "white",
      },
    },
  },
  fontSizes: [8, 10, 12, 13, 15, 16, 20, 24, 28, 30, 32, 48, 64, 72, 84],
  space: [0, 4, 8, 14, 16, 32, 48, 56, 64, 72, 84, 96, 128, 256, 512],
}
